
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'intermedium','intermedium.png','Banco Inter');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'bb','bb.png','Banco do Brasil');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'bradesco','bradesco.png','Bradesco');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'caixa','caixa.png','Caixa');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'itau','itau.png','Itaú');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'neon','neon.png','Neon');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'next','next.png','Next');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'nuconta','nuconta.png','Nuconta');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'santander','santander.png','Santander');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'agibank','agibank-1.png','Agibank');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'amazonia','amazonia.png','Amazonia');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'ame','ame-1.png','Ame Digital');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'bmg','bmg-6.png','BMG');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'brb','brb.png','BRB');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'brde','brde-4.png','BRDE');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'bs2','bs2-1.png','BS2');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'btgpactual','btgpactual-1.png','BTG Pactual');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'cacique','cacique.jpg','Banco Cacique ');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'pan','pan-7.png','Banco PAN');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'votorantim','votorantim-6.png','Banco Votorantim');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'nordeste','nordeste.png','Banco do Nordeste');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'banese','banese.jpg','Banese');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'banestes','banestes.png','Banestes');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'banif','banif.png','Banif');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'banpara','banpara.png','Banpara');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'banrisul','banrisul.png','Banrisul');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'bbm','bbm.png','Bbm');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'cetelem','cetelem-1.png','Cetelem');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'citibank','citibank.png','Citibank');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'cruzeirodosul','cruzeirodosul.jpg','Cruzeirodosul');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'daycoval','daycoval-1.png','Daycoval');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'digiplus','digiplus-1.png','Digi+');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'digio','digio.png','Digio');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'easynvest','easynvest-9.png','Easynvest');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'elliot','elliot-1.png','Elliot');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'genial','genial-1.png','Genial Investimentos');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'hsbc','hsbc.png','HSBC');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'iqoption','iqoption-1.png','IQ Option');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'iti','iti-1.png','Iti');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'mercadopago','mercadopago.png','Mercadopago');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'modalmais','modalmais-1.png','ModalMais');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'n26','n26-1.png','N26');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'original','original.png','Original');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'pagbank','pagbank-1.png','PagBank');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'paypal','paypal.png','Paypal');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'picpay','picpay-1.png','PicPay');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'recargapay','recargapay-1.png','Recargapay');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'rico','rico.png','Rico');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'safra','safra.png','Safra');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'sicoob','sicoob.png','Sicoob');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'sicredi','sicredi.png','Sicredi');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'sodexo','sodexo-1.png','Sodexo');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'sofisadireto','sofisadireto-1.png','Sofisa direto');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'unicred','unicred.png','Unicred');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'uniprime','uniprime-1.png','Uniprime');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'viacredi','viacredi-1.png','Viacredi');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'abcbrasil','abcbrasil-1.png','ABC Brasil');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'avenuesecuritie','avenuesecuritie-1.png','Avenue Securitie');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'bbva','bbva-1.png','BBVA');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'btgplus','btgplus-1.png','BTG +');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'interpj','interpj-1.png','Banco Inter PJ');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'benvisavale','benvisavale-1.png','Ben Visa Vale');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'c6bank','c6bank-2.png','C6 Bank');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'carteira','carteira.jpg','Carteira');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'celcoin','celcoin-1.png','Celcoin');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'contasimples','contasimples-1.png','ContaSimples');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'desjardins','desjardins-1.png','Desjardins Bank');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'icatu','icatu-1.png','Icatu');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'itaupersonnalite','itaupersonnalite-1.png','Itaú Personnalite');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'lhv','lhv-1.png','LHV');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'mercadobitcoin' ,'mercadobitcoin -1.png','Mercado Bitcoin ');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'mercantilbrasil','mercantilbrasil-1.png','Mercantil do Brasil');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'meliuz','meliuz-1.png','Méliuz');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'other','default.jpg','Outros');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'portoseguro','portoseguro-1.png','Porto Seguro');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'primacredi','primacredi-1.png','Primacredi');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'rci','rci-1.png','RCI');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'socialbank','socialbank-1.png','Social Bank');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'tangerine','tangerine-1.png','Tangerine');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'tribanco','tribanco-1.png','Tribanco');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'urpay','urpay-1.png','UrPay');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'vitreo','vitreo-2.png','Vitreo');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'wirecard','wirecard-1.png','Wirecard');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'woop','woop-1.png','Woop');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'xdex','xdex-1.png','Xdex');
    INSERT INTO bancos (bco_id,bco_codigo,bco_logo,bco_nome) values (0,'orama','orama-1.png','Órama');