
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'amex','amex.png','American Express');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'mastercard','mastercard.png','Mastercard');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'visa','visa.png','Visa');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'credicard','credicard-1.png','Credicard');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'diners','diners.png','Diners');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'elo','elo.png','Elo');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'nubank','nubank.png','Nubank');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'aura','aura-15.png','Aura');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'intermedium','intermedium.png','Banco Inter');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'bb','bb.png','Banco do Brasil');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'bradesco','bradesco.png','Bradesco');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'caixa','caixa.png','Caixa');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'hipercard','hipercard.png','Hipercard');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'itau','itau.png','Itaú');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'neon','neon.png','Neon');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'next','next.png','Next');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'santander','santander.png','Santander');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'agibank','agibank-1.png','Agibank');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'amazonia','amazonia.png','Amazonia');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'bmg','bmg-6.png','BMG');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'brb','brb.png','BRB');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'brde','brde-4.png','BRDE');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'bs2','bs2-1.png','BS2');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'cacique','cacique.jpg','Banco Cacique ');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'pan','pan-7.png','Banco PAN');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'votorantim','votorantim-6.png','Banco Votorantim');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'nordeste','nordeste.png','Banco do Nordeste');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'banese','banese.jpg','Banese');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'banestes','banestes.png','Banestes');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'banif','banif.png','Banif');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'banpara','banpara.png','Banpara');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'banrisul','banrisul.png','Banrisul');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'bbm','bbm.png','Bbm');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'cetelem','cetelem-1.png','Cetelem');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'citibank','citibank.png','Citibank');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'cruzeirodosul','cruzeirodosul.jpg','Cruzeirodosul');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'daycoval','daycoval-1.png','Daycoval');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'digiplus','digiplus-1.png','Digi+');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'digio','digio.png','Digio');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'fortbrasil','fortbrasil-1.png','Fortbrasil');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'hsbc','hsbc.png','HSBC');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'iti','iti-1.png','Iti');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'mais','mais-1.png','Mais!');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'n26','n26-1.png','N26');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'original','original.png','Original');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'pag','pag.png','Pag!');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'pagbank','pagbank-1.png','PagBank');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'pagseguro','pagseguro.png','Pagseguro');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'picpay','picpay-1.png','PicPay');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'safra','safra.png','Safra');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'sicoob','sicoob.png','Sicoob');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'sicredi','sicredi.png','Sicredi');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'sodexo','sodexo-1.png','Sodexo');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'sofisadireto','sofisadireto-1.png','Sofisa direto');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'submarino','submarino-1.png','Submarino');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'unicred','unicred.png','Unicred');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'uniprime','uniprime-1.png','Uniprime');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'viacredi','viacredi-1.png','Viacredi');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'abcbrasil','abcbrasil-1.png','ABC Brasil');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'acessobank','acessobank-1.png','Acesso Bank');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'activtrades','activtrades-1.png','ActivTrades');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'lojasamericanas','lojasamericanas-1.png','Americanas');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'bbva','bbva-1.png','BBVA');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'btgplus','btgplus-1.png','BTG +');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'interpj','interpj-1.png','Banco Inter PJ');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'binance','binance-1.png','Binance');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'c6bank','c6bank-2.png','C6 Bank');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'caju','caju-1.png','Caju');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'carrefour','carrefour-1.png','Carrefour');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'contasimples','contasimples-1.png','ContaSimples');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'coopercard','coopercard-1.png','Cooper Card');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'dmcard','dmcard-1.png','DM Card');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'default','default.png','Default');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'desjardins','desjardins-1.png','Desjardins Bank');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'ebanxgo','ebanxgo-1.png','EbanxGo');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'havan','havan-1.png','Havan');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'itaupersonnalite','itaupersonnalite-1.png','Itaú Personnalite');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'juno','juno-1.png','Juno');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'lhv','lhv-1.png','LHV');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'mercantilbrasil','mercantilbrasil-1.png','Mercantil do Brasil');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'meliuz','meliuz-1.png','Méliuz');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'other','default.jpg','Outros');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'portoseguro','portoseguro-1.png','Porto Seguro');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'proencamercado','proencamercado-1.png','Proença Mercados');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'rci','rci-1.png','RCI');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'senff','senff-1.png','Senff');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'shoptime','shoptime-1.png','Shoptime');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'socialbank','socialbank-1.png','Social Bank');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'sumup','sumup-1.png','Sumup');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'superdigital','superdigital-1.png','Superdigital');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'tangerine','tangerine-1.png','Tangerine');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'tribanco','tribanco-1.png','Tribanco');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'trigg','trigg.png','Trigg');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'tudoazul','tudoazul-1.png','Tudo Azul');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'urpay','urpay-1.png','UrPay');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'vr','vr-1.png','VR Benefícios');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'vitreo','vitreo-2.png','Vitreo');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'wirecard','wirecard-1.png','Wirecard');
    INSERT INTO bandeiras (ban_id,ban_codigo,ban_logo,ban_nome) values (0,'woop','woop-1.png','Woop');